includes:
  - ../app_locations.yml

################################################################################

settings.tk-nuke-projectsettings.shot_step:
  location: "@apps.tk-nuke-projectsettings.location"
